# Generated by Django 2.2.5 on 2019-10-02 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('lg_price', models.IntegerField()),
                ('sm_price', models.IntegerField()),
                ('cateqgory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.MenuCategory')),
            ],
        ),
    ]
