# Generated by Django 2.2.5 on 2019-10-03 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191002_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='menuCateg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('smPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lgPrice', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('menuCateg', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='categ_item', to='orders.menuCateg')),
            ],
        ),
    ]
