# Generated by Django 2.2.5 on 2019-10-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_items_menucateg'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucateg',
            name='image',
            field=models.ImageField(default='pizza-1.jpg', upload_to='images'),
        ),
    ]
