# Generated by Django 2.2.5 on 2019-10-04 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_auto_20191004_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='itemlist',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='total',
        ),
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsMenus', to='orders.Items'),
        ),
        migrations.AddField(
            model_name='orders',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_categ', to='orders.menuCateg'),
        ),
        migrations.AddField(
            model_name='orders',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
