# Generated by Django 2.2.5 on 2019-10-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191004_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
    ]
