# Generated by Django 2.2.5 on 2019-10-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20191004_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(default='pizza-1.jpg', upload_to='images/items'),
        ),
    ]
